# 日志配置，开发环境（dev）：打印 DEBUG 级别日志，输出到控制台 + 文件
logging:
  level:
    root: DEBUG
    # 关闭 Spring Boot 自动配置类的日志输出
    org.springframework.boot.autoconfigure: INFO
    org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter: ERROR
